footprint: [ [-0.07,-0.0875], [0.23,-0.0875], [0.23,0.0875], [-0.07,0.0875] ]
transform_tolerance: 0.2
obstacle_layer:
  enabled: true
  obstacle_range: 3.0
  raytrace_range: 3.5
  inflation_radius: 0.01
  track_unknown_space: false
  combination_method: 1
  observation_sources: lidar
  lidar: {sensor_frame: lidar, data_type: LaserScan, topic: /autodrive/nigel_1/lidar, marking: true, clearing: true}
inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0 # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius: 0.01 # max. distance from an obstacle at which costs are incurred for planning paths
static_layer:
  enabled: true
  map_topic: "/map"
