global_costmap:
  global_frame: map
  robot_base_frame: v1
  update_frequency: 2.0
  publish_frequency: 5.0
  transform_tolerance: 30
  width: 80
  height: 80
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
